name: Update nightly

# For testing
on: push

# on:
#   schedule:
#     - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - run: sudo apt-get install graphicsmagick

      - run: yarn install
      - run: yarn ts-node run.ts
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}



